# Generated by Django 4.1.2 on 2024-01-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0008_remove_result_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
